### ISSUE TITLE
Button overlapping when using with BetterEdit

### ISSUE THREAD

**Issue by Bigmancozmo** [HJfod/GDShare#12]
![image](https://user-images.githubusercontent.com/67850768/222969353-96299271-aabe-42ce-bdfa-c0b03e24ef6d.png)

**Comment by om3ga6400** [comment]
@HJfod

**Comment by om3ga6400** [comment]
@Bigmancozmo i found a solution; in megahackv7 make gd share mod higher load priority, this fixed the issue for me
