### ISSUE TITLE
Unable to use BetterEdit when inject GDShare and vice versa

### ISSUE THREAD

**Issue by l0zthrental** [HJfod/GDShare#5]

**Comment by HJfod** [comment]
Can you provide more information?
 • What modloader are you using?
 • How are you injecting the mods?
 • Do you have minhook.x32.dll in the folder with GeometryDash
exe?
 • Are the GDShare/BetterEdit buttons not showing up, or how are they incompatible?
 • Do you have the latest versions of both mods from the Discord server?

**Comment by Yaroslavkimeev** [comment]
GDShare/BetterEdit buttons not showing up

**Comment by Yaroslavkimeev** [comment]
1. For example: "WinRar"
2. I'm dragging files to a specific folder
3. Yes
4. GDShare/BetterEdit buttons not showing up
5. Yes

**Comment by HJfod** [comment]
WinRar is not a modloader, that's just an unzipper. What folder are you dragging the files into? Do you have any other mods installed?

**Comment by Yaroslavkimeev** [comment]
minhook.x32.dll and GDShare.dll into Geometry dash and png files into Resourses

**Comment by Yaroslavkimeev** [comment]
No, i haven't

**Comment by HJfod** [comment]
What modloader are you actually using? MegaHack v7?

**Comment by efwxx** [comment]
@Yaroslavkimeev you should look into using a modloader, such as GDHM and MHv7's builtin modloaders. if you're not interested in either, you can use [quickldr](https://github.com/HJfod/QuickLdr), which is relatively easy to set up.
