### ISSUE TITLE
I did a mistake and I need help (READ ISSUE)

### ISSUE THREAD

**Issue by KoLi717** [HJfod/GDShare#7]
So, I accidentally made all the files (gmd, gmd2, lvl) so they would open by notepad for some reason and I don't
 know how to put it back to normal. Please help me fix this.
![image_2022-07-22_182920712](https://user-images.githubusercontent.com/92122599/180576628-945d729e-9f58-4dc1-8669-50b8b256daf0.png)

**Comment by MegaSa1nt** [comment]
just ignore it
